# Generated by Django 5.2.11 on 2026-02-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='proup_name',
        ),
        migrations.AddField(
            model_name='telegram',
            name='description_name',
            field=models.TextField(default='Описание отсутствует', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegram',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.description'),
        ),
    ]
