# Generated by Django 5.2.11 on 2026-02-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_description_alter_telegram_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='description_name',
        ),
        migrations.AddField(
            model_name='telegram',
            name='group_name',
            field=models.TextField(default='Нет группы', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegram',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.group'),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
