# Generated by Django 5.2.11 on 2026-02-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_group_remove_telegram_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='group_name',
        ),
        migrations.AddField(
            model_name='telegram',
            name='description',
            field=models.TextField(default='нет описания', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
