# Generated by Django 6.0.2 on 2026-03-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_channeltype_alter_group_id_channel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeltype',
            options={'verbose_name': 'Тип канала', 'verbose_name_plural': 'Типы каналов'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описания'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AddField(
            model_name='channel',
            name='subscribers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество подписчиков'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.channeltype', verbose_name='Тип канала'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='description',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='telegram.channel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='telegram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='telegram.channel', verbose_name='Канал'),
        ),
    ]
