# Generated by Django 6.0.2 on 2026-03-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_alter_channeltype_options_alter_description_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default='нет описания', verbose_name='Название'),
            preserve_default=False,
        ),
    ]
