# Generated by Django 5.2.11 on 2026-03-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_alter_channel_description_alter_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='groups', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='groups', verbose_name='Изображение'),
        ),
    ]
