# Generated by Django 5.2.11 on 2026-03-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_channel_picture_group_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeltype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='channel_types/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='channels/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='Картинка'),
        ),
    ]
